# Generated by Django 2.1.5 on 2020-02-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=500, verbose_name='名称')),
                ('price', models.CharField(default='', max_length=50, verbose_name='总价')),
                ('unit_price', models.CharField(max_length=50, verbose_name='单价')),
                ('community_name', models.CharField(max_length=100, verbose_name='小区名')),
                ('region', models.CharField(max_length=50, verbose_name='区域')),
                ('type', models.CharField(max_length=50, verbose_name='户型')),
                ('construction_area', models.CharField(max_length=20, verbose_name='建筑面积')),
                ('orientation', models.CharField(max_length=10, verbose_name='朝向')),
                ('decoration', models.CharField(max_length=10, verbose_name='装修情况')),
                ('floor', models.CharField(max_length=15, verbose_name='楼层')),
                ('elevator', models.CharField(max_length=10, verbose_name='电梯')),
                ('purposes', models.CharField(max_length=15, verbose_name='房屋类型')),
                ('release_date', models.DateTimeField(verbose_name='挂牌时间')),
                ('house_structure', models.CharField(max_length=20, verbose_name='建筑类型')),
                ('image_urls', models.CharField(max_length=1500, verbose_name='房屋详情图')),
                ('from_url', models.CharField(max_length=100, verbose_name='房屋链接')),
            ],
            options={
                'verbose_name': 'house_info',
                'verbose_name_plural': 'house_info',
            },
        ),
    ]
