# Generated by Django 2.1.5 on 2020-02-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='api',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='api',
            name='update_time',
        ),
    ]
