# Generated by Django 2.1.5 on 2020-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='has_mean_price',
            new_name='mean_price',
        ),
        migrations.RenameField(
            model_name='elevator',
            old_name='has_mean_unit_price',
            new_name='mean_unit_price',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='has_el_num',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='no_el_num',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='no_mean_price',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='no_mean_unit_price',
        ),
        migrations.AddField(
            model_name='elevator',
            name='el_num',
            field=models.IntegerField(default=0, verbose_name='房源数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevator',
            name='has_ele',
            field=models.CharField(default=0, max_length=3, verbose_name='是否存在电梯'),
            preserve_default=False,
        ),
    ]
