# Generated by Django 2.1.5 on 2020-02-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20200227_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=9, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='api',
            name='release_date',
            field=models.DateField(verbose_name='挂牌时间'),
        ),
        migrations.AlterField(
            model_name='api',
            name='unit_price',
            field=models.DecimalField(decimal_places=1, max_digits=9, verbose_name='单价'),
        ),
    ]
