# Generated by Django 2.1.5 on 2020-03-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20200313_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='max_unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='最大单价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='min_unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='最小单价'),
            preserve_default=False,
        ),
    ]
