# Generated by Django 2.1.5 on 2020-03-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20200319_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=8, verbose_name='接口版本')),
                ('title', models.CharField(max_length=12, verbose_name='接口info')),
                ('name', models.CharField(max_length=30, verbose_name='小区名')),
                ('mean_unit_price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='单价均价')),
                ('region', models.ForeignKey(on_delete=None, to='house.Region', verbose_name='行政区划')),
            ],
            options={
                'verbose_name': 'Neighbor',
                'verbose_name_plural': 'Neighbor',
            },
        ),
        migrations.CreateModel(
            name='CommunityRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=8, verbose_name='接口版本')),
                ('title', models.CharField(max_length=12, verbose_name='接口info')),
                ('name', models.CharField(max_length=30, verbose_name='小区名')),
                ('mean_unit_price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='单价均价')),
                ('region', models.ForeignKey(on_delete=None, to='house.Region', verbose_name='行政区划')),
            ],
            options={
                'verbose_name': 'CommunityRange',
                'verbose_name_plural': 'CommunityRange',
            },
        ),
    ]
