# Generated by Django 2.1.5 on 2020-04-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_community_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='lat',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='纬度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='lng',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='经度'),
            preserve_default=False,
        ),
    ]
